# safelist
branches:
  only:
  - master
  - develop
  - test

language: cpp
compiler: gcc
dist: xenial
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install libsfml-dev
script: make && git ls-files src/ | xargs clang-format -i && git diff --exit-code && ./bin/test
